vich_uploader:
    db_driver: orm

    mappings:
        tasks:
            uri_prefix: /images/tasks
            upload_destination: '%kernel.project_dir%/public/images/tasks'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

