vich_uploader:
    db_driver: orm

    mappings:
        tasks:
            uri_prefix: /images/tasks
            upload_destination: '%kernel.project_dir%/public/images/tasks'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
        invoices_pdf:
            uri_prefix: /clients/invoices/pdf
            upload_destination: '%kernel.project_dir%/public/invoices/pdf'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        invoices_images:
            uri_prefix: /clients/invoices/images
            upload_destination: '%kernel.project_dir%/public/invoices/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

