vich_uploader:
    db_driver: orm

    mappings:
        tasks:
            uri_prefix: /images/tasks
            upload_destination: '%kernel.project_dir%/public/images/tasks'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        client:
            uri_prefix: /images/client
            upload_destination: '%kernel.project_dir%/public/images/client'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        surveyor:
            uri_prefix: /images/surveyor
            upload_destination: '%kernel.project_dir%/public/images/surveyor'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

